version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
  app:
    build:
      context: ./rails # Dockerfileのあるディレクトリ
      dockerfile: Dockerfile.dev # 開発環境用
    command: rails server -b 0.0.0.0 -p 3000
    volumes:
      - ./rails:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  webpack:
    build: 
      context: ./rails/frontend # Dockerfileのあるディレクトリ
      dockerfile: Dockerfile.dev # 開発環境用
    command: npm run start
    working_dir: "/app/frontend"
    volumes:
      - ./rails/frontend:/app/frontend
    ports:
      - "3500:3500"
    depends_on:
      - app
volumes:
  postgres-data: